CREATE DATABASE doingsdone
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE projects (
id_name INT AUTO_INCREMENT PRIMARY KEY, 
title CHAR(64) NOT NULL,
id_user INT NOT NULL
);

CREATE TABLE users (
id_user INT AUTO_INCREMENT PRIMARY KEY,
name_user CHAR(128) NOT NULL UNIQUE,
email CHAR(128) NOT NULL UNIQUE,
password CHAR(64) NOT NULL UNIQUE,
date_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE tasks(
id_task INT AUTO_INCREMENT PRIMARY KEY,
dt_creat TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
status BOOL DEFAULT FALSE,
name TEXT NOT NULL,
file CHAR(128) UNIQUE,
deadline DATE NULL,
id_name INT NOT NULL,
id_user INT NOT NULL
);

CREATE INDEX id_name ON tasks(id_name);
CREATE INDEX id_user ON tasks(id_user);
CREATE INDEX id_user ON projects(id_user);

